    INF SelunaPkg/Driver/GpioButtons/GpioButtons.inf
    INF SelunaPkg/Driver/SimpleFbDxe/SimpleFbDxe.inf

    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/CipherDxe/CipherDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/EnvDxe/EnvDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/FuseInfoDxe/FuseInfoDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/HashDxe/HashDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/MacDxe/MacDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/MinidumpTADxe/MinidumpTADxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/PILDxe/PILDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/QcomBds/QcomBds.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/RNGDxe/RngDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SdccDxe/SdccDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/VariableDxe/VariableDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf

    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
    # INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ClockDxe/ClockDxe.inf
    ## TODO: Review Patch granularity
    INF QcomPkg/PatchedBinaries/ClockDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/FontDxe/FontDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/GpiDxe/GpiDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/HWIODxe/HWIODxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/I2CDxe/I2CDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/NpaDxe/NpaDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/QcomMpmTimerDxe/QcomMpmTimerDxe.inf

    ## Fails with not found then reboot
    ## INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf

    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SmemDxe/SmemDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SPIDxe/SPIDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/TsensDxe/TsensDxe.inf

    ## Hangs
    ## INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/TzDxe/ScmDxeLA.inf

    ## Fails with not found then reboot
    ## INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/TzDxe/TzDxeLA.inf

    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/ULogDxe/ULogDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf

    ## Needs VerifiedBootDxe
    ## INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf

    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
    INF Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/VcsDxe/VcsDxe.inf

    FILE DRIVER = 6b38f7b4-ad98-40e9-9093-aca2b5a253c4 {
            SECTION PE32 = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.efi
            SECTION UI = "DiskIoDxe"
    }

    FILE DRIVER = 1fa1f39e-feff-4aae-bd7b-38a070a3b609 {
            SECTION PE32 = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.efi
            SECTION UI = "PartitionDxe"
    }

    FILE DRIVER = 3adf8dda-1850-44c5-8c63-bb991849bc6f {
            SECTION UI = "HashDxe"
            SECTION PE32 = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/HashDxe/HashDxe.efi
    }

    FILE DRIVER = 5f0937cd-73f9-445e-b320-bb6fd5d3cbde {
            SECTION UI = "CipherDxe"
            SECTION PE32 = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/CipherDxe/CipherDxe.efi
    }

    FILE DRIVER = b0d3689e-11f8-43c6-8ece-023a29cec35b {
            SECTION UI = "RngDxe"
            SECTION PE32 = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/QcomPkg/Drivers/RNGDxe/RngDxe.efi
    }

    FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
        SECTION UI = "BDS_Menu.cfg"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/BDS_Menu.cfg
    }

    FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
        SECTION UI = "Glogo.bmp"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Glogo.bmp
    }

    FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030790 {
        SECTION UI = "splash.bmp"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/splash.bmp
    }

    FILE FREEFORM = 0D0D6B72-21D1-4249-8C09-9EABE9C198F7 {
        SECTION UI = "Fijit_symbol.bmp"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Fijit_symbol.bmp
    }

    FILE FREEFORM = 02A7D6B7-12D1-4255-8C09-9EABE24198F7 {
        SECTION UI = "Color_Glogo_456.bmp"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Color_Glogo_456.bmp
    }

    FILE FREEFORM = 77D6B723-2441-6891-1209-EA9BE9C19812 {
        SECTION UI = "Color_Glogo_408.bmp"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Color_Glogo_408.bmp
    }

    FILE FREEFORM = 77A064F4-CF79-4DE6-9337-9304D4FAFCF9 {
        SECTION UI = "Panel_sim_panel_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sim_panel_cmd.xml
    }

    FILE FREEFORM = A9E001FA-7578-401B-B3D6-5F3337997877 {
        SECTION UI = "Panel_truly_rm69090_amoled_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_truly_rm69090_amoled_cmd.xml
    }

    FILE FREEFORM = 940B76D7-C1F5-4C8F-8A90-3014D12CC335 {
        SECTION UI = "Panel_truly_rm6d030_amoled_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_truly_rm6d030_amoled_cmd.xml
    }

    FILE FREEFORM = B77A50A1-5838-4D40-9BA4-89DC4D40638D {
        SECTION UI = "Panel_boe_amoled_wf012fbm_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_boe_amoled_wf012fbm_cmd.xml
    }

    FILE FREEFORM = D4255A49-A35D-4115-918E-BD526A914898 {
        SECTION UI = "Panel_boe_amoled_rm690c0_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_boe_amoled_rm690c0_cmd.xml
    }

    FILE FREEFORM = 0BE86199-82D9-4523-B934-BFCE6C85C6B0 {
        SECTION UI = "Panel_sdc_amoled_amb120dd01_evt1_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sdc_amoled_amb120dd01_evt1_cmd.xml
    }

    FILE FREEFORM = F0E89CE2-D176-44FF-851F-39A9FFFE7AA3 {
        SECTION UI = "Panel_sdc_amoled_amb120dd01_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sdc_amoled_amb120dd01_cmd.xml
    }

    FILE FREEFORM = 491EB004-6900-6811-5BA8-E22CFF56C9CE {
        SECTION UI = "Panel_vnx_amoled_rm690c0_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_vnx_amoled_rm690c0_cmd.xml
    }

    FILE FREEFORM = AC7C0AE3-EAFC-4500-9DE2-3054A56EBB4C {
        SECTION UI = "Panel_boe_amoled_wj013pgm_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_boe_amoled_wj013pgm_cmd.xml
    }

    FILE FREEFORM = B65CF3E3-325B-4E20-833C-4F89B27B4D2F {
        SECTION UI = "Panel_boe_amoled_wj014sgm_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_boe_amoled_wj014sgm_cmd.xml
    }

    FILE FREEFORM = 65C1ECE6-C4F0-49A4-838C-BB2A0A3DF9A8 {
        SECTION UI = "Panel_sdc_amoled_amb127fp01_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sdc_amoled_amb127fp01_cmd.xml
    }

    FILE FREEFORM = F6447E24-AE27-4A2B-9B4A-9FB398087965 {
        SECTION UI = "Panel_sdc_amoled_amb133ha01_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sdc_amoled_amb133ha01_cmd.xml
    }

    FILE FREEFORM = D36B8CDA-DCFD-42B9-A5A2-03CC40EC7CCE {
        SECTION UI = "Panel_sdc_amoled_amb149hb01_cmd.xml"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/Panel_sdc_amoled_amb149hb01_cmd.xml
    }

    FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
        SECTION UI = "SecParti.cfg"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/SecParti.cfg
    }

    FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
        SECTION UI = "uefipil.cfg"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/uefipil.cfg
    }

    FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
        SECTION UI = "QcomChargerCfg.cfg"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/QcomChargerCfg.cfg
    }

    FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
        SECTION UI = "BATTERY.PROVISION"
        SECTION RAW = Seluna/BOOT.XF.4.3-00257-ATHERTONLAZ-1/RawFiles/BATTERY.PROVISION
    }